{{/* A) Opaque Secret for TELE_TOKEN */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "secret.name is required" .Values.secret.name }}
type: Opaque
stringData:
  {{ required "secret.key is required" .Values.secret.key }}: {{ required "secret.value must be set (use --set-string secret.value=…)" .Values.secret.value | quote }}
---
{{/* B) Docker registry creds for GHCR */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name | default "ghcr-creds" }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {{- $server := default "ghcr.io" .Values.registry.server -}}
    {{- $user   := required "registry.username is required" .Values.registry.username -}}
    {{- $pass   := required "registry.password is required" .Values.registry.password -}}
    {{- $email  := default "ci@example.com" .Values.registry.email -}}
    {{- $auth   := printf "%s:%s" $user $pass | b64enc -}}
    {{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" $server $user $pass $email $auth | nindent 4 }}